spring:
  application:
    name: policy-service
  config:
    import: optional:configserver:http://localhost:8888

server:
  port: 8082

# Database configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/policydb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Eureka client configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
